name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKER_NAME: ${{ secrets.DOCKERHUB_NAME }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build
        run: |
          docker build . -t $DOCKER_USER/$DOCKER_NAME
      - name: docker push
        run: |
          docker push $DOCKER_USER/$DOCKER_NAME
